% puprisa_MultiExpFitDialog.m
% popup dialog for specifying fit parameters for multi exponential fit

%
% returns results in fit parameter structure containing:
%
% fitParm.InstResponse 
% fitParm.A1
% fitParm.T1
% fitParm.A2
% fitParm.T2
% fitParm.A1L
% fitParm.T1L
% fitParm.A2L
% fitParm.T2L
% fitParm.InstRespL 
% fitParm.A1U
% fitParm.T1U
% fitParm.A2U
% fitParm.T2U
% fitParm.InstRespU 
% fitParm.type


function fitParm = puprisa_MultiExpFitDialog()
    
    f=figure('WindowStyle','modal','units','pixels',...
        'Name','Fit Parameters','NumberTitle','off');
    pos = get(f,'position');
    pos(3:4) = [550 280];
    set(f,'position',pos);
    
        
    pbCancel = uicontrol('style','pushbutton',...
        'string','Cancel','Callback',@(s,e) uiresume(gcbf),...
        'position',[400    10    60    20],...
        'tag','pbCancel');
    
    pbOK = uicontrol('style','pushbutton',...
        'string','OK','Callback', @okButtonCallback,...
        'position',[480    10    60    20],...
        'tag','pbOK' );
    
   
    
     
    %Initial conditions for exponential fit
    txtInCond = uicontrol('style','text','FontSize',10,...
        'string','Initial conditions for exponential fit:',...
        'position',[16   210    220    18],...
        'tag','txtInCond');
    
     
    
    % instantaneous response
    txtInstResponse = uicontrol('style','text',...
        'string','Instantaneous response:',...
        'position',[16   180    135    18],...
        'tag','txtInstResponse');
    edInstResponse = uicontrol('style','edit',...
        'string','0',...
        'position',[156   180   40    18],...
        'tag','edInstResponse');
    
    
    txA1 = uicontrol('style','text',...
        'string','A1:',...
        'position',[16    150    25    20],...
        'tag','txA1');
    edA1 = uicontrol('style','edit',...
        'string','-1',...
        'position',[43    150    25    20],...
        'tag','edA1');
    
    txT1 = uicontrol('style','text',...
        'string','T1 (ps):',...
        'position',[77    150    45    20],...
        'tag','txT1');
    edT1 = uicontrol('style','edit',...
        'string','1',...
        'position',[125    150    25    20],...
        'tag','edT1');
    
    txA2 = uicontrol('style','text',...
        'string','A2:',...
        'position',[16    120    25    20],...
        'tag','txA2');
    edA2 = uicontrol('style','edit',...
        'string','-0.3',...
        'position',[43    120    25    20],...
        'tag','edA2');
    
    txT2 = uicontrol('style','text',...
        'string','T2 (ps):',...
        'position',[77    120    45    20],...
        'tag','txT2');
    edT2 = uicontrol('style','edit',...
        'string','5',...
        'position',[127    120    25    20],...
        'tag','edT2');
    
    
    Frame1 = uicontrol('style','frame',...
        'position',[258    40    280    230],...
        'tag','Frame1');
    
    txtFrame1 = uicontrol('style','text','FontSize',11,...
        'string','Bounds for exponential fit:',...
        'position',[262   245    180    18],...
        'tag',' txtFrame1');
    
    %Lower bounds for exponential fit
    txtInCondL = uicontrol('style','text','FontSize',9,...
        'string','Lower bounds:',...
        'position',[276   105    100    18],...
        'tag','txtInCondL');
    
    txA1L = uicontrol('style','text',...
        'string','A1:',...
        'position',[286    80    25    20],...
        'tag','txA1L');
    edA1L = uicontrol('style','edit',...
        'string','-Inf',...
        'position',[313    80    25    20],...
        'tag','edA1L');
    
    txT1L = uicontrol('style','text',...
        'string','T1 (ps):',...
        'position',[347    80    45    20],...
        'tag','txT1L');
    edT1L = uicontrol('style','edit',...
        'string','0',...
        'position',[395    80    25    20],...
        'tag','edT1L');
    
    txInstRespL = uicontrol('style','text',...
        'string','Inst. Resp:',...
        'position',[439    80    55    20],...
        'tag','txInstRespL');
    edInstRespL = uicontrol('style','edit',...
        'string','-Inf',...
        'position',[499    80    25    20],...
        'tag','edInstRespL');
    
    txA2L = uicontrol('style','text',...
        'string','A2:',...
        'position',[286    50    25    20],...
        'tag','txA2L');
    edA2L = uicontrol('style','edit',...
        'string','-Inf',...
        'position',[313    50    25    20],...
        'tag','edA2L');
    
    txT2L = uicontrol('style','text',...
        'string','T2 (ps):',...
        'position',[347    50    45    20],...
        'tag','txT2L');
    edT2L = uicontrol('style','edit',...
        'string','0',...
        'position',[397    50    25    20],...
        'tag','edT2L');
    
    %Upper bounds for exponential fit
    txtInCondU = uicontrol('style','text','FontSize',9,...
        'string','Upper bounds:',...
        'position',[276   205    100    18],...
        'tag','txtInCondU');
    
    txA1U = uicontrol('style','text',...
        'string','A1:',...
        'position',[286    180    25    20],...
        'tag','txA1U');
    edA1U = uicontrol('style','edit',...
        'string','0',...
        'position',[313    180    25    20],...
        'tag','edA1U');
    
    txT1U = uicontrol('style','text',...
        'string','T1 (ps):',...
        'position',[347    180    45    20],...
        'tag','txT1U');
    edT1U = uicontrol('style','edit',...
        'string','Inf',...
        'position',[395    180    25    20],...
        'tag','edT1U');
    
    txInstRespU = uicontrol('style','text',...
        'string','Inst. Resp:',...
        'position',[439    180    55    20],...
        'tag','txInstRespU');
    edInstRespU = uicontrol('style','edit',...
        'string','Inf',...
        'position',[499    180    25    20],...
        'tag','edInstRespU');
    
    txA2U = uicontrol('style','text',...
        'string','A2:',...
        'position',[286    150    25    20],...
        'tag','txA2U');
    edA2U = uicontrol('style','edit',...
        'string','0',...
        'position',[313    150    25    20],...
        'tag','edA2U');
    
    txT2U = uicontrol('style','text',...
        'string','T2 (ps):',...
        'position',[347    150    45    20],...
        'tag','txT2U');
    edT2U = uicontrol('style','edit',...
        'string','Inf',...
        'position',[397    150    25    20],...
        'tag','edT2U');
    
        
   
     txtNoOfExp = uicontrol('style','text',...
        'string','No. of exponentials:',...
        'position',[16   67    110    20],...
        'tag','txtNoOfExp');
    
     edNoOfExp = uicontrol('style','popupmenu',...
        'string',{'1' '2'},'Value',2,...
        'position',[140   69   42    20],...
        'tag','edNoOfExp');
    
    hButton = uibuttongroup('units','pixels','Position',[16 24 210 25],'tag','hButton');
    positiveButton = uicontrol('Style','Radio','String','Positive',...
        'pos',[5 4 80 18],'parent',hButton,'HandleVisibility','off','tag','positiveButton');
    negativeButton = uicontrol('Style','Radio','String','Negative',...
        'pos',[120 4 80 18],'parent',hButton,'HandleVisibility','off','tag','negativeButton');
    
    % Initialize some button group properties.
    set(hButton,'SelectionChangeFcn',@selcallback);
    set(hButton,'SelectedObject',negativeButton);  
    
    
    uiwait(f);
    
    fitParm = getappdata(f,'fitParm');
    
    close(f);
end

function okButtonCallback( src, evt )
   
    % get parameters
    h = guihandles(gcbf);
    
    
    fitParm.InstResponse = str2num(get(h.edInstResponse,'string'));
    fitParm.A1 = str2num(get(h.edA1,'string'));
    fitParm.T1 = str2num(get(h.edT1,'string'));
    fitParm.A2 = str2num(get(h.edA2,'string'));
    fitParm.T2 = str2num(get(h.edT2,'string'));
    fitParm.A1L = str2num(get(h.edA1L,'string'));
    fitParm.T1L = str2num(get(h.edT1L,'string'));
    fitParm.A2L = str2num(get(h.edA2L,'string'));
    fitParm.T2L = str2num(get(h.edT2L,'string'));
    fitParm.InstRespL = str2num(get(h.edInstRespL,'string'));
    fitParm.A1U = str2num(get(h.edA1U,'string'));
    fitParm.T1U = str2num(get(h.edT1U,'string'));
    fitParm.A2U = str2num(get(h.edA2U,'string'));
    fitParm.T2U = str2num(get(h.edT2U,'string'));
    fitParm.InstRespU = str2num(get(h.edInstRespU,'string'));
    fitParm.NoOfExp = get(h.edNoOfExp,'Value');
    
    typeSelect = get(get(h.hButton,'SelectedObject'),'string');
    if(strcmp(typeSelect,'Positive'))
        fitParm.type = 1 ;
    elseif(strcmp(typeSelect,'Negative'))
        fitParm.type = -1 ;
    end
    
    setappdata(gcbf,'fitParm',fitParm);

    uiresume(gcbf);
end

function selcallback( src, evt )

    h = guihandles(gcbf);
    Selection = get(get(src,'SelectedObject'),'string');
    if(strcmp(Selection,'Positive'))%set positive fit parameters
        set(h.edA1,'string',0.7);
        set(h.edT1,'string',0.2);
        set(h.edA2,'string',0.1);
        set(h.edT2,'string',10);
        
        %bounds
        set(h.edA1U,'string',Inf);
        set(h.edT1U,'string',Inf);
        set(h.edA2U,'string',Inf);
        set(h.edT2U,'string',Inf);
        set(h.edA1L,'string',0);
        set(h.edT1L,'string',0);
        set(h.edA2L,'string',0);
        set(h.edT2L,'string',0);
    elseif(strcmp(Selection,'Negative'))%set negative fit parameters
        set(h.edA1,'string',-0.3);
        set(h.edT1,'string',0.5);
        set(h.edA2,'string',-0.1);
        set(h.edT2,'string',5);
        
        %bounds
        set(h.edA1U,'string',0);
        set(h.edT1U,'string',Inf);
        set(h.edA2U,'string',0);
        set(h.edT2U,'string',Inf);
        set(h.edA1L,'string',-Inf);
        set(h.edT1L,'string',0);
        set(h.edA2L,'string',-Inf);
        set(h.edT2L,'string',0);
    end
end
