% puprisa_exportGIFDialog.m
% popup dialog for specifying parameters for animated GIF export of
% a z stack
%
% returns results in export parameter structure containing:
%
% exportParm.fileName
% exportParm.loop
% exportParm.startSlice
% exportParm.endSlice
% exportParm.delay
% exportParm.backForth

function exportParm = puprisa_exportGIFDialog(nSlices)
    if nargin == 0      % defaults so this still works if run from F5
        nSlices = 2;
    end

    f=figure('WindowStyle','modal','units','pixels',...
        'Name','GIF Export Parameters','NumberTitle','off');
    pos = get(f,'position');
    pos(3:4) = [329 186];
    set(f,'position',pos);
    
    
    
    pbCancel = uicontrol('style','pushbutton',...
        'string','Cancel','Callback',@(s,e) uiresume(gcbf),...
        'position',[169    13    60    20],...
        'tag','pbCancel');
    
    pbOK = uicontrol('style','pushbutton',...
        'string','OK','Callback', @okButtonCallback,...
        'position',[244    12    60    20],...
        'tag','pbOK' );
    
    txtFileName = uicontrol('style','text',...
        'string','File name:',...
        'position',[16   149    60    20],...
        'tag','txtFileName');
    edFileName = uicontrol('style','edit',...
        'string','exported.gif',...
        'position',[84   151   224    20],...
        'tag','edFileName');
   
    
    txtStartSlice = uicontrol('style','text',...
        'string','Start slice:',...
        'position',[18   118    60    20]);
    edStartSlice = uicontrol('style','edit',...
        'string','1',...
        'position',[90   118    60    20],...
        'tag','edStartSlice');
    
    txtEndSlice = uicontrol('style','text',...
        'string','End slice:',...
        'position',[19    89    60    20]);
    edEndSlice = uicontrol('style','edit',...
        'string',num2str(nSlices),...
        'position',[92    90    60    20],...
        'tag','edEndSlice');
     
    cbLoop = uicontrol('style','checkbox',...
        'string','Loop','value',1,...
        'position',[212    86    60    20],...
        'tag','cbLoop');
    cbBackForth = uicontrol('style','checkbox',...
        'string','Back and forth','value',1,...
        'position',[212    62   100    20],...
        'tag','cbBackForth');
    
    
    txDelay = uicontrol('style','text',...
        'string','Delay:',...
        'position',[17    53    60    20],...
        'tag','txDelay');
    edDelay = uicontrol('style','edit',...
        'string','0',...
        'position',[93    54    60    20],...
        'tag','edDelay');
        
    uiwait(f);
    
    exportParm = getappdata(f,'exportParm');
    
    close(f);
end

function okButtonCallback( src, evt )
    % get parameters
    h = guihandles(gcbf);
    exportParm.fileName = get(h.edFileName,'string');
    exportParm.loop = get(h.cbLoop,'value');
    exportParm.startSlice = str2num(get(h.edStartSlice,'string'));
    exportParm.endSlice = str2num(get(h.edEndSlice,'string'));
    exportParm.delay = str2num(get(h.edDelay,'string'));
    exportParm.backForth = get(h.cbBackForth,'value');
    
    
    setappdata(gcbf,'exportParm',exportParm);

    uiresume(gcbf);
end
