% puprisa_ArtImagingDialog.m
% popup dialog for specifying fit parameters for double exponential fit

%
% returns results in fit parameter structure containing:
%
% fitParm.MinDelay
% fitParm.MaxDelay
% fitParm.A1
% fitParm.T1
% fitParm.A2
% fitParm.T2
% fitParm.A1L
% fitParm.T1L
% fitParm.A2L
% fitParm.T2L
% fitParm.A1U
% fitParm.T1U
% fitParm.A2U
% fitParm.T2U

% fitParm.snrThresholdHigh
% fitParm.snrThresholdLow
% fitParm.snrThresholdAbs
% fitParm.fileName
% fitParm.bin
% fitParm.type


function fitParm = puprisa_ArtImaingDialog()
    
    f=figure('WindowStyle','modal','units','pixels',...
        'Name','Fit Parameters','NumberTitle','off');
    pos = get(f,'position');
    pos(3:4) = [800 280];
    set(f,'position',pos);
    
        
    pbCancel = uicontrol('style','pushbutton',...
        'string','Cancel','Callback',@(s,e) uiresume(gcbf),...
        'position',[660    10    60    20],...
        'tag','pbCancel');
    
    pbOK = uicontrol('style','pushbutton',...
        'string','OK','Callback', @okButtonCallback,...
        'position',[730    10    60    20],...
        'tag','pbOK' );
    
   
    %Min delay
    txtMinDelay = uicontrol('style','text',...
        'string','MinDelay (ps):',...
        'position',[16   160    80    20],...
        'tag','txtMinDelay');
    edMinDelay = uicontrol('style','edit',...
        'string','0.71',...
        'position',[110   160   60    20],...
        'tag','edMinDelay');
    
    %Max Delay
    txtMaxDelay = uicontrol('style','text',...
        'string','MaxDelay (ps):',...
        'position',[16   133    80    20],...
        'tag','txtMaxDelay');
    edMaxDelay = uicontrol('style','edit',...
        'string','Inf',...
        'position',[110   133   60    20],...
        'tag','edMaxDelay');
     
    %Initial conditions for exponential fit
    txtInCond = uicontrol('style','text','FontSize',10,...
        'string','Initial conditions for exponential fit:',...
        'position',[16   89    220    18],...
        'tag','txtInCond');
    
    txA1 = uicontrol('style','text',...
        'string','A1:',...
        'position',[16    60    25    20],...
        'tag','txA1');
    edA1 = uicontrol('style','edit',...
        'string','-1',...
        'position',[43    60    25    20],...
        'tag','edA1');
    
    txT1 = uicontrol('style','text',...
        'string','T1 (ps):',...
        'position',[77    60    45    20],...
        'tag','txT1');
    edT1 = uicontrol('style','edit',...
        'string','1',...
        'position',[125    60    25    20],...
        'tag','edT1');
    
    txA2 = uicontrol('style','text',...
        'string','A2:',...
        'position',[16    30    25    20],...
        'tag','txA2');
    edA2 = uicontrol('style','edit',...
        'string','-0.3',...
        'position',[43    30    25    20],...
        'tag','edA2');
    
    txT2 = uicontrol('style','text',...
        'string','T2 (ps):',...
        'position',[77    30    45    20],...
        'tag','txT2');
    edT2 = uicontrol('style','edit',...
        'string','5',...
        'position',[127    30    25    20],...
        'tag','edT2');
    
    
    Frame1 = uicontrol('style','frame',...
        'position',[258    20    225    230],...
        'tag','Frame1');
    
    txtFrame1 = uicontrol('style','text','FontSize',11,...
        'string','Bounds for exponential fit:',...
        'position',[262   225    180    18],...
        'tag',' txtFrame1');
    
    %Lower bounds for exponential fit
    txtInCondL = uicontrol('style','text','FontSize',9,...
        'string','Lower bounds:',...
        'position',[276   85    100    18],...
        'tag','txtInCondL');
    
    txA1L = uicontrol('style','text',...
        'string','A1:',...
        'position',[286    60    25    20],...
        'tag','txA1L');
    edA1L = uicontrol('style','edit',...
        'string','-Inf',...
        'position',[313    60    25    20],...
        'tag','edA1L');
    
    txT1L = uicontrol('style','text',...
        'string','T1 (ps):',...
        'position',[347    60    45    20],...
        'tag','txT1L');
    edT1L = uicontrol('style','edit',...
        'string','0',...
        'position',[395    60    25    20],...
        'tag','edT1L');
    
    txA2L = uicontrol('style','text',...
        'string','A2:',...
        'position',[286    30    25    20],...
        'tag','txA2L');
    edA2L = uicontrol('style','edit',...
        'string','-Inf',...
        'position',[313    30    25    20],...
        'tag','edA2L');
    
    txT2L = uicontrol('style','text',...
        'string','T2 (ps):',...
        'position',[347    30    45    20],...
        'tag','txT2L');
    edT2L = uicontrol('style','edit',...
        'string','0',...
        'position',[397    30    25    20],...
        'tag','edT2L');
    
    %Upper bounds for exponential fit
    txtInCondU = uicontrol('style','text','FontSize',9,...
        'string','Upper bounds:',...
        'position',[276   185    100    18],...
        'tag','txtInCondU');
    
    txA1U = uicontrol('style','text',...
        'string','A1:',...
        'position',[286    160    25    20],...
        'tag','txA1U');
    edA1U = uicontrol('style','edit',...
        'string','0',...
        'position',[313    160    25    20],...
        'tag','edA1U');
    
    txT1U = uicontrol('style','text',...
        'string','T1 (ps):',...
        'position',[347    160    45    20],...
        'tag','txT1U');
    edT1U = uicontrol('style','edit',...
        'string','Inf',...
        'position',[395    160    25    20],...
        'tag','edT1U');
    
    txA2U = uicontrol('style','text',...
        'string','A2:',...
        'position',[286    130    25    20],...
        'tag','txA2U');
    edA2U = uicontrol('style','edit',...
        'string','0',...
        'position',[313    130    25    20],...
        'tag','edA2U');
    
    txT2U = uicontrol('style','text',...
        'string','T2 (ps):',...
        'position',[347    130    45    20],...
        'tag','txT2U');
    edT2U = uicontrol('style','edit',...
        'string','Inf',...
        'position',[397    130    25    20],...
        'tag','edT2U');
    
   
    
    hBin = uibuttongroup('units','pixels','Position',[16 205 170 50],'tag','hBin');
    textBin = uicontrol('Style','text','String','Binning:','FontSize',9,...
        'pos',[0 20 60 25],'parent',hBin,'HandleVisibility','off','tag','textBin');
    enableBin = uicontrol('Style','Radio','String','Enable',...
        'pos',[13 4 80 18],'parent',hBin,'HandleVisibility','off','tag','enableBin');
    disableBin = uicontrol('Style','Radio','String','Disable',...
        'pos',[80 4 60 18],'parent',hBin,'HandleVisibility','off','tag','disableBin');
   
    set(hBin,'SelectedObject',disableBin);  
    
    
    %Signal Threshold
    txtSnrThresholdLow = uicontrol('style','text',...
        'string','Signal Threshold Low (%)',...
        'position',[580   230    133    20],...
        'tag','txtSnrThresholdLow');
    edSnrThresholdLow = uicontrol('style','edit',...
        'string','20',...
        'position',[720   230   60    20],...
        'tag','edSnrThresholdLow');
    
    txtSnrThresholdHigh = uicontrol('style','text',...
        'string','Signal Threshold High (%)',...
        'position',[580   200    133    20],...
        'tag','txtSnrThresholdHigh');
    edSnrThresholdHigh = uicontrol('style','edit',...
        'string','100',...
        'position',[720   200   60    20],...
        'tag','edSnrThresholdHigh');
    
    txtSnrThresholdABS = uicontrol('style','text',...
        'string','Signal Threshold (Absolute)',...
        'position',[580   170    140    20],...
        'tag','txtSnrThresholdABS');
    edSnrThresholdABS = uicontrol('style','edit',...
        'string','-0.2',...
        'position',[727   170   52    20],...
        'tag','edSnrThresholdABS');
    
    txtFilename = uicontrol('style','text',...
        'string','File name:',...
        'position',[580   140    60    18],...
        'tag','txtFilename');
    edFilename = uicontrol('style','edit',...
        'string','IndigoPoint',...
        'position',[580   115   210    22],...
        'tag','edFilename');
    
     txtNoOfExp = uicontrol('style','text',...
        'string','No. of exponentials:',...
        'position',[580   77    110    20],...
        'tag','txtNoOfExp');
    
     edNoOfExp = uicontrol('style','popupmenu',...
        'string',{'1' '2'},'Value',2,...
        'position',[700   79   42    20],...
        'tag','edNoOfExp');
    
    hButton = uibuttongroup('units','pixels','Position',[580 44 210 25],'tag','hButton');
    positiveButton = uicontrol('Style','Radio','String','Positive',...
        'pos',[5 4 80 18],'parent',hButton,'HandleVisibility','off','tag','positiveButton');
    negativeButton = uicontrol('Style','Radio','String','Negative',...
        'pos',[120 4 80 18],'parent',hButton,'HandleVisibility','off','tag','negativeButton');
    
    % Initialize some button group properties.
    set(hButton,'SelectionChangeFcn',@selcallback);
    set(hButton,'SelectedObject',negativeButton);  
   
   
    
    
    uiwait(f);
    
    fitParm = getappdata(f,'fitParm');
    
    close(f);
end

function okButtonCallback( src, evt )
   
    % get parameters
    h = guihandles(gcbf);
    
    fitParm.MinDelay = str2num(get(h.edMinDelay,'string'));
    fitParm.MaxDelay = str2num(get(h.edMaxDelay,'string'));
    fitParm.A1 = str2num(get(h.edA1,'string'));
    fitParm.T1 = str2num(get(h.edT1,'string'));
    fitParm.A2 = str2num(get(h.edA2,'string'));
    fitParm.T2 = str2num(get(h.edT2,'string'));
    fitParm.A1L = str2num(get(h.edA1L,'string'));
    fitParm.T1L = str2num(get(h.edT1L,'string'));
    fitParm.A2L = str2num(get(h.edA2L,'string'));
    fitParm.T2L = str2num(get(h.edT2L,'string'));
    fitParm.A1U = str2num(get(h.edA1U,'string'));
    fitParm.T1U = str2num(get(h.edT1U,'string'));
    fitParm.A2U = str2num(get(h.edA2U,'string'));
    fitParm.T2U = str2num(get(h.edT2U,'string'));
    fitParm.snrThresholdHigh = str2num(get(h.edSnrThresholdHigh,'string'));
    fitParm.snrThresholdLow = str2num(get(h.edSnrThresholdLow,'string'));
    fitParm.snrThresholdAbs = str2num(get(h.edSnrThresholdABS,'string'));
    fitParm.NoOfExp = get(h.edNoOfExp,'Value');
    
    fitParm.fileName = get(h.edFilename,'string');
    
    binSelect = get(get(h.hBin,'SelectedObject'),'string');
    if(strcmp(binSelect,'Enable'))
        fitParm.bin = 1 ;
    else
        fitParm.bin = 0 ;
    end
    
    typeSelect = get(get(h.hButton,'SelectedObject'),'string');
    if(strcmp(typeSelect,'Positive'))
        fitParm.type = 1 ;
    elseif(strcmp(typeSelect,'Negative'))
        fitParm.type = -1 ;
    end
    
    setappdata(gcbf,'fitParm',fitParm);

    uiresume(gcbf);
end

function selcallback( src, evt )

    h = guihandles(gcbf);
    Selection = get(get(src,'SelectedObject'),'string');
    if(strcmp(Selection,'Positive'))%set positive fit parameters
        set(h.edA1,'string',0.7);
        set(h.edT1,'string',2);
        set(h.edA2,'string',0.5);
        set(h.edT2,'string',5);
        set(h.edSnrThresholdABS,'string',0.5);
        %bounds
        set(h.edA1U,'string',Inf);
        set(h.edT1U,'string',Inf);
        set(h.edA2U,'string',Inf);
        set(h.edT2U,'string',Inf);
        set(h.edA1L,'string',0);
        set(h.edT1L,'string',0);
        set(h.edA2L,'string',0);
        set(h.edT2L,'string',0);
    elseif(strcmp(Selection,'Negative'))%set negative fit parameters
        set(h.edA1,'string',-0.3);
        set(h.edT1,'string',0.5);
        set(h.edA2,'string',-0.1);
        set(h.edT2,'string',5);
        set(h.edSnrThresholdABS,'string',-0.2);
        %bounds
        set(h.edA1U,'string',0);
        set(h.edT1U,'string',Inf);
        set(h.edA2U,'string',0);
        set(h.edT2U,'string',Inf);
        set(h.edA1L,'string',-Inf);
        set(h.edT1L,'string',0);
        set(h.edA2L,'string',-Inf);
        set(h.edT2L,'string',0);
    end
end
